fix: fix os.date("!*t", os.time()) will not get UTC date time issue
yuin/gopher-lua pull request #433
Opened 2023-04-12 11:25 UTC by ttys3

Fixes `os.date("!*t", os.time())` will not get UTC date time issue

2023-05-29 05:37 UTC, yuin requested changes

2023-05-29 05:37 UTC, yuin commented on baselib_test.go
> +	t.Setenv("TZ", "Asia/Tokyo")
I think we should rollback the `TZ` variable.

2023-05-30 08:07 UTC, yuin commented
@ttys3 Sorry for misunderstanding your PR.
I had thought `os.Setenv` but you used `t.Setenv` so you do not need to rollback the TZ envvar.
Could you add `t.Setenv` again?

2023-05-30 12:44 UTC, ttys3 commented
> @ttys3 Sorry for misunderstanding your PR. I had thought `os.Setenv` but you used `t.Setenv` so you do not need to rollback the TZ envvar. Could you add `t.Setenv` again?

done. PTAL

2023-05-30 17:07 UTC, merged